### ISSUE TITLE
Make Table unresponsive on mobile on our wish.

### ISSUE THREAD

**Issue by roker15** [JiHong88/SunEditor#1014]
Sometimes table have more columns (>3) , so when you see the table on mobile , it shrinks and content inside it looks very bad. So i want my table to be of same size as on desktop and not to be responsive on mobile screen.
Is it possible?

**Comment by JiHong88** [comment]
ex)
```css
.sun-editor-editable table.se-table-size-auto {
  min-width: 500px;
}
```
