### ISSUE TITLE
Looks like we don't need "user-select: none" by default

### ISSUE THREAD

**Issue by SystemChanger** [JiHong88/suneditor#1262]
https://github.com/JiHong88/suneditor/blob/1fc9b55bb712d7617148f44f0e5208e52749b8f7/src/assets/css/suneditor.css#L8

I think that user should be possible to select and copy text even in disabled state of suneditor.
I was looking for way to add this possibility in my project and ended up with following css in my project:
```css
.sun-editor {
    user-select: auto;
    -o-user-select: auto;
    -moz-user-select: auto;
    -khtml-user-select: auto;
    -webkit-user-select: auto;
    -ms-user-select: auto;
}
```
Are there any reasons to restrict this by default? My suggest is to allow user selection by default.
