### ISSUE TITLE
 On the demo webpage, the input box is exposed.

### ISSUE THREAD

**Issue by kimindu** [JiHong88/SunEditor#1381]
On the demo webpage, the input box is exposed.
Please look at the screenshot.

![screen81448](https://github.com/JiHong88/suneditor/assets/4196963/5e2147df-c4c7-4ed3-a4c3-db394482c0e6)

**Comment by sillycube** [comment]
The same here. But I find the issue in my dev and prod site.

**Comment by Monabbir-Ahmmad** [comment]
You can temporarily fix the issue by adding the following CSS in your global css file
```css
/* Hide input but leave it accessible*/
body div.se-container > input {
  display: none;
}
```

**Comment by Monabbir-Ahmmad** [comment]
This issue also occurs when using the package. It seems like you can temporarily fix the issue by adding the following CSS inside your global CSS file.

```css
/* Hide input but leave it accessible*/
body div.se-container > input {
  display: none;
}
```
