### ISSUE TITLE
Strange behaviour during writing in table cell

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#193]
Hello,

thanks for your project. It's really great but I want to report an issue which I found during testing table functionalities. When table is resized to full width I see strange behaviour about automatically resizing the columns width during writing text in the cell. This behaviour not appears in not-resized mode of the table. I uploaded the gif which shows this behaviour.

[https://i.imgur.com/csU5QlE.gifv](https://i.imgur.com/csU5QlE.gifv)

I wanted to ask if this beahaviour is intentional or it's a bug?

Kind regards,
Adrian

**Comment by JiHong88** [comment]
Hi,

It is intended behavior.
Currently if you want to fix the width of the columns, you need to modify the [sunedtir-contents.css:246](https://github.com/JiHong88/SunEditor/blob/master/src/assets/css/suneditor-contents.css#L246).
```css
.sun-editor-editable table {
    ...
    /** table-layout: auto; */
    table-layout: fixed;
    ...
}
```
Thank you.
