### ISSUE TITLE
Paste content with styling issue

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#248]
Hello,

I want to thank you once again for this editor. Very good job!
After your newest release I used attributesWhitelist to keep style attribute while pasting following elements: `table, tbody, thead, tr, td`. I have following problem: some of styles are just missing. What is really strange, that this happens only when I have version from NPM. When I downloaded release version and added whole dist folder, then suneditor behaves as it should. 

In my case, the border-type style disappear (I noticed only this, maybe something else). Please check it on following codesandboxes - please select and copy table which is under text editor and try to paste it. For this example I disabled your custom CSS styles for tables.

NPM example: [https://i.imgur.com/wb0cuzC.gifv](https://i.imgur.com/wb0cuzC.gifv) 
NPM sandbox: [https://codesandbox.io/s/suneditor-paste-npm-9mwt9](https://codesandbox.io/s/suneditor-paste-npm-9mwt9)

non-NPM example: [https://i.imgur.com/6en9YRp.gifv](https://i.imgur.com/6en9YRp.gifv)
non-NPM: [https://codesandbox.io/s/suneditor-paste-no-npm-e7fs4](https://codesandbox.io/s/suneditor-paste-no-npm-e7fs4)

I will be thankful for any investigation in this case and fixing this bug, because this is one of most important functionality in my application (pasting every style).

Kind regards,
Adrian

**Comment by JiHong88** [comment]
Hi
Both modes work fine.
```html
<table style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; border-width: initial; border-style: none; border-color: initial;">
    <tbody>
        <tr style="height: 14pt;">
            <td style="width: 198.45pt; border-top: 1pt solid black; border-right: 1pt solid black; border-bottom: 1pt solid black; padding: 0in 5.4pt; height: 14pt;">
```
However, I noticed that "styles.css" is defined differently.
NPM sandbox > styles.css
```css
body {
  font-family: sans-serif;
}

.sun-editor-editable table td,
.sun-editor-editable table th {
  border: none !important;
}
```
non-NPM sandbox > styles.css
```css
body {
  font-family: sans-serif;
}

.sun-editor-editable table td {
  border: none;
}

.sun-editor-editable table td.se-table-selected-cell {
  border: none;
}
```
Try the test again.
Thank you.
