### ISSUE TITLE
테이블 이슈

### ISSUE THREAD

**Issue by kimhyeongyu** [JiHong88/SunEditor#309]
테이블 글 입력할때 셀 고정이 아니라, 한글자 입력할때마다 옆으로 늘어나는 현상이 있습니다.
![Screenshot_20200403-145624_Chrome](https://user-images.githubusercontent.com/39076893/78329157-e89a9380-75bb-11ea-89a2-61847212210d.jpg)

**Comment by JiHong88** [comment]
테이블 레이아웃이 오토로 설정되어 있어서 그렇습니다. 
[suneditor-contents.css#L273](https://github.com/JiHong88/SunEditor/blob/master/src/assets/css/suneditor-contents.css#L273)

고정하려면 table-layout 속성을 재정의 해주면 됩니다.
```css
.sun-editor-editable table {
  table-layout: fixed;
}
```
