### ISSUE TITLE
Question: Format and Paragraph submenu display format set by custom class itself

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#325]
I am trying to create a div paragraph centered vertically and horisontally by setting a custom class to a < div> element via Format and/or Paragraph submenu. This works fine. But since the submenus list items seem to take the form/class of the customized element itself, I get a empty large area where I instead would like simple text/button name. See: 
![image](https://user-images.githubusercontent.com/58078302/78943155-8100ae80-7abb-11ea-93ea-763ea2048174.png)
("Absatz" is the prior item, current item text/button text is not even shown). I tried both Paragraph and Format submenus. Any chance to get this behaviour changed - or have I made a mistake?

**Comment by JiHong88** [comment]
How did you set the options?

**Comment by MRB60** [comment]
> 	formats: ['p', 
	{
                    tag: 'div', // Tag name
                    name: 'Center div', // default: tag name
                    command: 'replace', // default: "replace"
                    class: '__se__format__replace_mb-center-text'
                    // Class names must always begin with "__se__format__(replace, range, free)_"
                  }

**Comment by JiHong88** [comment]
I tested it like this.
```javascript
formats: [
        'p',
        {
            tag: 'div', // Tag name
            name: 'Center div', // default: tag name
            command: 'replace', // default: "replace"
            class: '__se__format__replace_mb-center-text' // Class names must always begin with "se__format(replace, range, free)_"
        }
    ],
```
Show me the css code of the "__se__format__replace_mb-center-text" class.

**Comment by MRB60** [comment]
> .mb-center-text {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 50vh;
}

**Comment by JiHong88** [comment]
<img width="335" alt="스크린샷 2020-04-10 오후 9 07 25" src="https://user-images.githubusercontent.com/13191953/78989705-4eb08900-7b6f-11ea-87cf-e2d7b96f9c03.png">
Due to the height(50vh) property of the 'div', the bottom buttons are pushed out and cannot be seen.

You can express by giving css separately in the ".sun-editor" and ".sun-editoor-editable" fields.

```css
.sun-editor-editable .__se__format__replace_mb-center-text {
    justify-content: center;
    align-items: center;
    border: 3px solid green;
}

.sun-editor .__se__format__replace_mb-center-text {
    display: flex!important;
    justify-content: center;
    align-items: center;
    /** height: 50vh; **/
    border: 3px solid green;
}
```
