### ISSUE TITLE
Document Style Editor 

### ISSUE THREAD

**Issue by PleachiM** [JiHong88/suneditor#432]
Is there an easy way to implement this with your editor? 
- Document Styling (A4 Page)
- PageBreaks for Print

https://ckeditor.com/ckeditor-4/demo/#document

**Comment by JiHong88** [comment]
> Document Styling (A4 Page)

You can change the style as follows.
```css
.sun-editor .se-wrapper {
  padding: 30px 60px;
  background-color: #eee;
}

.sun-editor .se-wrapper .se-wrapper-inner {
  border: 1px solid #ccc;
}
```

> PageBreaks for Print

You can check the height of the editor in the "onChange" event ("context.element.wysiwyg"),
Based on this, add a line to "context.element.relative".
Add it to the css of the line:
```css
pointer-events: none;
backface-visibility: hidden;
-webkit-backface-visibility: hidden;
-moz-backface-visibility: hidden;
```
