### ISSUE TITLE
Button Sizing

### ISSUE THREAD

**Issue by nagyvilmos** [JiHong88/SunEditor#444]
Is it possible to manage the size of the buttons used in the toolbar?

In out use case, we will often have multiple wysiwyg editors on a page and, while I don't want to hide the toolbar, I would like to reduce used real estate.

**Comment by JiHong88** [comment]
Hi @nagyvilmos 

Resize the button by giving the editor a class depending on the situation.
```css
.sun-editor#your-editor-id .se-btn {
  width: 24px;
  height: 24px;
}
```
