### ISSUE TITLE
Add a code highlight button for selection

### ISSUE THREAD

**Issue by hudsonfoo** [JiHong88/SunEditor#472]
Video describing the issue: https://www.loom.com/share/79a9a519a9254d1f9b8832a31a1edb98

**Comment by JiHong88** [comment]
You need to use the `textStyle` button and `textStyles` option.
```javascript
textStyles: [
  name: "Code",
  class: "se-code",
  tag: "span"
]
```
```css
se-code: {
  font-family: monospace;
  color: #666;
  background-color: #f9f9f9;
  border: 1px solid #e1e1e1;
  border-radius: 2px;
}
```
I'll add a code format to the default `textStyles`
