### ISSUE TITLE
How to change z-index of Link modal?

### ISSUE THREAD

**Issue by Bogdan1001** [JiHong88/suneditor#519]
Hello  thank you for great product!

Please can you hint me how to change z-index of the modal which appears on Link button click?

**Comment by Bogdan1001** [comment]
P.S. Actually figure out it without help of z-index with popupDisplay: 'local'

**Comment by JiHong88** [comment]
Hi @Bogdan1001 
You can redefine the css class.
```css
.sun-editor .se-dialog {
  z-index: 2147483647; /* default value */
}
```
