### ISSUE TITLE
Height percentage doesn't seem to work

### ISSUE THREAD

**Issue by guido-visser** [JiHong88/SunEditor#627]
When using `height: "100%"`, I expect it to stretch to the bottom of the parent div. However, passing a percentage doesn't seem to do anything. Passing `100px` or `auto` does work.

Playground:
https://codepen.io/dagorbattle/pen/ExNgoqO

I expect the height of the editor to fill to the red border. When the content gets larger than the 100%, then it should overflow the `.se-wrapper-inner`

**Comment by JiHong88** [comment]
@guido-visser Is it working properly in the vanilla JS version?

**Comment by guido-visser** [comment]
> @guido-visser Is it working properly in the vanilla JS version?

The playground provided is a codepen of the Vanilla JS version

**Comment by JiHong88** [comment]
@guido-visser Should the editor screen be responsive display?

**Comment by JiHong88** [comment]
```css
.sun-editor {
  height: 100%;
}
.sun-editor .se-wrapper {
  height: calc(100% - 94px - 16px); /* 100% - toolbar offsetHeight - bottom resizing bar offsetHeight */
}
```
