### ISSUE TITLE
Customize font submenu dropdown

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/SunEditor#746]
Hi @JiHong88 ,

I am trying to add a check icon on the font, font size submenu dropdown whenever user selection is active.
please find the screenshot for reference:
![Group 3](https://user-images.githubusercontent.com/22369081/117537307-9f6a0e00-b01d-11eb-8d29-ef4744040200.png)

is there any possible way to do that in suneditor?

Thank you

**Comment by JiHong88** [comment]
@gopal1996 You can add it in the following way:  
```css
.sun-editor .se-submenu.se-list-font-size .se-list-inner .se-list-basic li button.active:after {
 content: ""
}
```
Find out how to put a checkmark.
