### ISSUE TITLE
(Default) in fontSize is not working

### ISSUE THREAD

**Issue by keepyourcool** [JiHong88/SunEditor#860]
When I use fontSize (I have been using it through the buttonList) the (default) option in the dropdown does nothing. Technically it should be changing the font size of the editor to default font size which i have defined as 14px in defaultStyle.  Has someone else faced this issue? Please help me out. Please find below my suneditor component.
`<SunEditor 
      defaultValue={this.props.defaultValue ? this._addPTag(this.props.defaultValue):""}
      width="100%"
      height = {50}
      onBlur = {this._onBlurHandler}
      onInput = {this._onInputHandler}
      onChange = {this._onChangeHandler}
      setOptions = {{
        defaultStyle: 'font-family: cursive; font-size: 10px;',
        plugins: [
          emojiSubmenu,
          fontSizeSubmenu
      ],
        buttonList:[['bold', 'italic', 'underline','fontColor','fontSize',{
          name: 'emoji_submenu',
          dataCommand: 'emoji_submenu',
          buttonClass: '',
          title: 'Emoji',
          dataDisplay: 'submenu',
          innerHTML: '<span class="se-icon-text">🙂</span>',
      },'codeView']],
        fontSize:[12,18],
        colorList:["#EE82EE","#4B0082","#0000FF","#228B22", "#FFFF00", "#FFA500", "#FF0000"],
        shortcutsHint:false,
        pasteTagsBlacklist : 'span|br',
        tagsBlacklist:'br|div|pre|blockquote|ol|ul|li|hr|figure|figcaption|img|iframe|audio|video|table|thead|tbody|tr|th|td|a|var|ins|s|strike|del|sub|sup|code|svg|path'
        }}
      
       />`

Thanks in Advance

**Comment by JiHong88** [comment]
@keepyourcool The default value removes the set size. 
Set the default size in CSS. 

This is default style of the editor's contents.
```css
.sun-editor-editable {
    font-family: Helvetica Neue;
    font-size: 13px;
    color: #333;
    background-color: #fff;
    line-height: 1.5;
    word-break: normal;
    word-wrap: break-word;
    padding: 16px;
    margin: 0;
}
```
